ChartName          = "Line and Symbol"; 
ChartType          = XYCHART; 
ChartWidth         = 300;  
ChartHeight        = 250;  
Background         = (xffffff,NONE,3,,TILE,black);  
BottomTics         = ("ON",black,"Comic Sans MS",12,null,null);  
LeftTics           = ("ON",black,"SansSerif",12,null,null); 
Header             = ("<%=request.getParameter("name")%>",black,SansSerif,12,0);  
HeaderBox  		   = (null,NONE,1,"null",TILE,black);
LeftScale          = (0,100);  
LeftAxisTitle      = ("Percent of time Atrazine value is\nless than indicated value",black,"TimesRoman",12,90);  
BottomAxisTitle    = ("",black,"TimesRoman",12,0);  
LineSets           = ("std dev",black),("std dev",black),("std dev",black),("std dev",black),("std dev",black),("std dev",black),("std dev",black),("std dev",black),("std dev",black),("Predicted",xe31a1c),("Threshold",red);  
LineSymbol         = (,,FILLED,black,0,,,0),(,,FILLED,black,0,,,0),(,,FILLED,black,0,,,0),(,,FILLED,black,0,,,0),(,,FILLED,black,0,,,0),(,,FILLED,black,0,,,0),(,,FILLED,black,0,,,0),(,,FILLED,black,0,,,0),(,,FILLED,black,0,,,0),(DIAMOND,12,FILLED,xe31a1c,0,,,0),(CIRCLE,1,FILLED,red,0,,,0);  
LineStyle          = (SOLID,1,BLACK,),(SOLID,1,BLACK,),(SOLID,1,BLACK,),(SOLID,1,BLACK,),(SOLID,1,BLACK,),(SOLID,1,BLACK,),(SOLID,1,BLACK,),(SOLID,1,BLACK,),(SOLID,1,BLACK,),(SOLID,2,xe31a1c,),(DOTTED,2,red,);  
<%=request.getParameter("lineset")%>
LineSet11          = (<%=request.getParameter("threshold")%>,0),(<%=request.getParameter("threshold")%>,100);
LineAxis           = (BOTTOM,LEFT),(BOTTOM,LEFT),(BOTTOM,LEFT),(BOTTOM,LEFT),(BOTTOM,LEFT),(BOTTOM,LEFT),(BOTTOM,LEFT),(BOTTOM,LEFT),(BOTTOM,LEFT);  
BottomAxisTitle    = ("Atrazine concentration in ug/L",black,"TimesRoman",12,0);  
BottomTicLayout    = (SKIP,8,1);  
BottomScaleMode    = (LOG,10);  
#BottomScale        = (<%=request.getParameter("scalemin")%>,<%=request.getParameter("scalemax")%>,);  
BottomScale        = (0.0010,100,);  
BottomFormat       = (FLOAT,);
RightTitle         = (" ",white,"TimesRoman",16,0); 
GridLine           = (BOTH,DOTTED,1); 
Grid               = (xC2C4C6,white,black,,TILE);  
GridAxis           = (BOTTOM,LEFT); 
RightTitleBox      = (null,NONE,2,null,TILE,black); 
AntiAlias          = "ON"; 
DwellLabel         = ("",black,"SansSerif",10,0); 